apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  labels:
    app: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: hashicorp/http-echo
        args:
        - "-text=Hello from Simple API"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api
spec:
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP 